const STORAGE_KEY = "countly-counters";
const HUNT_COUNTERS_KEY = "countly-yellow-hunt-counters";
const THEME_KEY = "countly-theme";
const HUNT_KEY = "countly-yellow-hunt";
const TUTORIAL_KEY = "countly-tutorial-seen";
const LANGUAGE_KEY = "countly-language";
const translations = {
  en: {
    language: "Language", yourCounters: "Your counters", heroTitle: "Keep track of what matters.", addCounter: "Add new counter", howToPlay: "How to play",
    guideCopy: "Spot a yellow car for <strong>1 point</strong>. Log each find and see who can spot the most.",
    totalCount: "Total count", activeCounters: "Active counters", renameHint: "Click a counter’s name to rename it", keepItSimple: "Keep it simple.", viewTutorial: "View tutorial again", quickTour: "QUICK TOUR", skipIntro: "Skip Tutorial", continue: "Continue", finish: "Finish",
    tip: "TIP", play: "PLAY", car: "Car", tapToAdjust: "Tap to adjust", untitled: "Untitled counter", counter: "Counter", resetConfirm: "Reset all counters to zero?", emptyTitle: "Your counter space is ready.", emptyCopy: "Add a counter to get started.",
    chooseLanguage: "Choose language", darkMode: "Switch to dark mode", lightMode: "Switch to light mode", activateHunt: "Activate Yellow Hunt mode", exitHunt: "Exit Yellow Hunt mode", resetAll: "Reset all counters", counterName: "Counter name", remove: "Remove", increase: "Increase", decrease: "Decrease", carAria: "Log a yellow car for",
    tutorials: [
      ["Make it yours", "Add as many counters as you need, then give each one a name so everything stays easy to find."],
      ["Count in a tap", "Use the plus and minus controls on any card to keep your numbers moving. Your progress is saved automatically."],
      ["Try Yellow Hunt", "Switch on Yellow Hunt for the road game: log yellow cars for 1 point."],
      ["Choose your language", "Open the globe menu to choose English, German, Spanish, Mandarin Chinese, or Hindi."],
      ["Set the mood", "Toggle between light and dark mode whenever you like. Countly remembers your preference."],
      ["Start fresh", "Use reset whenever you want to bring every counter back to zero and begin a new round."]
    ]
  },
  de: {
    language: "Sprache", yourCounters: "Deine Zähler", heroTitle: "Behalte im Blick, was zählt.", addCounter: "Neuen Zähler hinzufügen", howToPlay: "So wird gespielt", guideCopy: "Entdecke ein gelbes Auto für <strong>1 Punkt</strong>. Erfasse jeden Fund und finde die meisten.", totalCount: "Gesamtzahl", activeCounters: "Aktive Zähler", renameHint: "Klicke auf den Namen eines Zählers, um ihn umzubenennen", keepItSimple: "Einfach halten.", viewTutorial: "Tutorial erneut ansehen", quickTour: "KURZTOUR", skipIntro: "Intro überspringen", continue: "Weiter", finish: "Fertig", tip: "TIPP", play: "SPIEL", car: "Auto", tapToAdjust: "Antippen zum Ändern", untitled: "Unbenannter Zähler", counter: "Zähler", resetConfirm: "Alle Zähler auf null zurücksetzen?", emptyTitle: "Dein Zählerbereich ist bereit.", emptyCopy: "Füge einen Zähler hinzu.", chooseLanguage: "Sprache auswählen", darkMode: "Dunkelmodus aktivieren", lightMode: "Hellmodus aktivieren", activateHunt: "Yellow Hunt aktivieren", exitHunt: "Yellow Hunt beenden", resetAll: "Alle Zähler zurücksetzen", counterName: "Name des Zählers", remove: "Zähler entfernen", increase: "Erhöhen", decrease: "Verringern", carAria: "Gelbes Auto für", tutorials: [["Mach es zu deinem", "Füge beliebig viele Zähler hinzu und gib ihnen Namen, damit alles leicht zu finden bleibt."], ["Mit einem Tipp zählen", "Nutze Plus und Minus auf jeder Karte. Dein Fortschritt wird automatisch gespeichert."], ["Yellow Hunt ausprobieren", "Aktiviere Yellow Hunt: Gelbe Autos zählen 1 Punkt."], ["Sprache auswählen", "Öffne das Globusmenü und wähle deine Sprache."], ["Stimmung festlegen", "Wechsle jederzeit zwischen hellem und dunklem Modus."], ["Neu beginnen", "Setze alle Zähler zurück, um eine neue Runde zu starten."]]
  },
  es: {
    language: "Idioma", yourCounters: "Tus contadores", heroTitle: "Lleva el control de lo que importa.", addCounter: "Añadir nuevo contador", howToPlay: "Cómo jugar", guideCopy: "Encuentra un coche amarillo por <strong>1 punto</strong>. Registra cada hallazgo y descubre quién encuentra más.", totalCount: "Cuenta total", activeCounters: "Contadores activos", renameHint: "Haz clic en el nombre para cambiarlo", keepItSimple: "Mantenlo simple.", viewTutorial: "Ver tutorial de nuevo", quickTour: "GUÍA RÁPIDA", skipIntro: "Omitir introducción", continue: "Continuar", finish: "Terminar", tip: "CONSEJO", play: "JUEGO", car: "Coche", tapToAdjust: "Toca para ajustar", untitled: "Contador sin título", counter: "Contador", resetConfirm: "¿Restablecer todos los contadores a cero?", emptyTitle: "Tu espacio de contadores está listo.", emptyCopy: "Añade un contador para empezar.", chooseLanguage: "Elegir idioma", darkMode: "Cambiar a modo oscuro", lightMode: "Cambiar a modo claro", activateHunt: "Activar Yellow Hunt", exitHunt: "Salir de Yellow Hunt", resetAll: "Restablecer contadores", counterName: "Nombre del contador", remove: "Eliminar contador", increase: "Aumentar", decrease: "Disminuir", carAria: "Coche amarillo para", tutorials: [["Hazlo tuyo", "Añade los contadores que necesites y ponles nombre para encontrar todo fácilmente."], ["Cuenta con un toque", "Usa los controles más y menos. Tu progreso se guarda automáticamente."], ["Prueba Yellow Hunt", "Activa Yellow Hunt: los coches amarillos valen 1 punto."], ["Elige tu idioma", "Abre el menú del globo para elegir idioma."], ["Cambia el ambiente", "Alterna entre el modo claro y oscuro cuando quieras."], ["Empieza de cero", "Restablece los contadores para comenzar una ronda nueva."]]
  },
  zh: {
    language: "语言", yourCounters: "你的计数器", heroTitle: "记录重要的事情。", addCounter: "添加新计数器", howToPlay: "玩法", guideCopy: "发现黄色汽车得<strong>1分</strong>。记录每次发现，看看谁发现得最多。", totalCount: "总计数", activeCounters: "活动计数器", renameHint: "点击计数器名称即可重命名", keepItSimple: "保持简单。", viewTutorial: "再次查看教程", quickTour: "快速导览", skipIntro: "跳过介绍", continue: "继续", finish: "完成", tip: "提示", play: "游戏", car: "汽车", tapToAdjust: "点击调整", untitled: "未命名计数器", counter: "计数器", resetConfirm: "将所有计数器重置为零？", emptyTitle: "计数器空间已准备好。", emptyCopy: "添加一个计数器开始吧。", chooseLanguage: "选择语言", darkMode: "切换到深色模式", lightMode: "切换到浅色模式", activateHunt: "开启 Yellow Hunt", exitHunt: "退出 Yellow Hunt", resetAll: "重置所有计数器", counterName: "计数器名称", remove: "删除计数器", increase: "增加", decrease: "减少", carAria: "记录黄色汽车，计数器为", tutorials: [["打造专属计数器", "添加需要的计数器并命名，让一切都易于查找。"], ["轻触即可计数", "使用加减按钮更新数字，进度会自动保存。"], ["试试 Yellow Hunt", "开启 Yellow Hunt：黄色汽车得1分。"], ["选择语言", "打开地球图标菜单选择语言。"], ["调整氛围", "随时切换浅色和深色模式。"], ["重新开始", "重置所有计数器，开始新一轮。"]]
  },
  hi: {
    language: "भाषा", yourCounters: "आपके काउंटर", heroTitle: "जो ज़रूरी है उसका हिसाब रखें।", addCounter: "नया काउंटर जोड़ें", howToPlay: "कैसे खेलें", guideCopy: "पीली कार के लिए <strong>1 अंक</strong> पाएं। हर खोज दर्ज करें और देखें किसने सबसे ज़्यादा पाया।", totalCount: "कुल गिनती", activeCounters: "सक्रिय काउंटर", renameHint: "नाम बदलने के लिए काउंटर के नाम पर क्लिक करें", keepItSimple: "सरल रखें।", viewTutorial: "ट्यूटोरियल फिर देखें", quickTour: "त्वरित परिचय", skipIntro: "परिचय छोड़ें", continue: "जारी रखें", finish: "समाप्त", tip: "सुझाव", play: "खेल", car: "कार", tapToAdjust: "बदलने के लिए टैप करें", untitled: "बिना नाम का काउंटर", counter: "काउंटर", resetConfirm: "सभी काउंटर शून्य पर रीसेट करें?", emptyTitle: "आपका काउंटर स्थान तैयार है।", emptyCopy: "शुरू करने के लिए काउंटर जोड़ें।", chooseLanguage: "भाषा चुनें", darkMode: "डार्क मोड पर जाएं", lightMode: "लाइट मोड पर जाएं", activateHunt: "Yellow Hunt शुरू करें", exitHunt: "Yellow Hunt से बाहर निकलें", resetAll: "सभी काउंटर रीसेट करें", counterName: "काउंटर का नाम", remove: "काउंटर हटाएं", increase: "बढ़ाएं", decrease: "घटाएं", carAria: "पीली कार दर्ज करें, काउंटर", tutorials: [["इसे अपना बनाएं", "जितने काउंटर चाहिए जोड़ें और उन्हें नाम दें ताकि सब आसानी से मिल सके।"], ["एक टैप में गिनें", "प्लस और माइनस बटन का उपयोग करें। प्रगति अपने आप सेव होती है।"], ["Yellow Hunt आज़माएं", "Yellow Hunt चालू करें: पीली कार 1 अंक देती है।"], ["भाषा चुनें", "भाषा चुनने के लिए ग्लोब मेनू खोलें।"], ["मूड सेट करें", "जब चाहें लाइट और डार्क मोड बदलें।"], ["फिर से शुरू करें", "नई शुरुआत के लिए सभी काउंटर रीसेट करें।"]]
  }
};
let currentLanguage = "en";
